name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Node.js and dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # You can specify the Node.js version here

    - name: Install dependencies
      run: npm install

    # Build the project
    - name: Build project
      run: npm run build

    # Sync dist folder to S3
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'        # Upload the dist folder
